# This script turns OFF protection mode for CONFIRE SHERLOCK.
# You should reboot the system right after susccessfull execution of this script.
#
# Author: STÜBER SYSTEMS GmbH
# Last updated: 05.12.2018
# Version: 0.1
#
# Requirements: 
# You need to get an api token which is generated by CONFIRE SHERLOCK. 
# See https://doc.sherlock3.stueber.co.uk/console.html for documentation.

$apiToken = "FE520676B1A1D933674F3632EAEEB163D1E88244F5EB1DEDABAB2319EEA010EB"

cmd /c "C:\Program Files\Stueber Systems\Confire Sherlock\cfs" set-protectionMode Off $apiToken
